services:
  uniceps_frontend:
    build: .
    container_name: uniceps_site
    restart: always
    expose:
      - "3000"
    env_file:
      - .env.production
    networks:
      - trioverse-network

networks:
  trioverse-network:
    external: true